name: CI pipeline

on:
  push:
#    branches:
#      - main
#    paths-ignore:
#      - README.md


jobs:
  pipeline:
   uses: susanto-dev/devops-infra/.github/workflows/ci-pipeline.yml@develop
   secrets: inherit
   with:
     component: 'react-native'
