name: CI pipeline

on:
  push:
#    branches:
#      - main
#    paths-ignore:
#      - README.md


jobs:
  build:
   uses: susanto-dev/devops-infra/.github/workflows/ci-pipeline.yml@develop
   secrets: inherit
   with:
     component: 'react-native'

#  deploy-to-dev:
#   needs: [build]
#   uses: susanto-dev/devops-infra/.github/workflows/cd.yml@develop
#   secrets: inherit
#   with:
#     repository: 'react-native-component'
#     version: '${{ needs.build.outputs.build_version }}'
#     environment: 'dev'
#     component: 'react-native'
#
#  deploy-to-uat:
#   needs: [build]
#   uses: susanto-dev/devops-infra/.github/workflows/cd.yml@develop
#   secrets: inherit
#   with:
#     repository: 'react-native-component'
#     version: '${{ needs.build.outputs.build_version }}'
#     environment: 'uat'
#     component: 'react-native'
#
#  deploy-to-prod:
#   needs: [build]
#   uses: susanto-dev/devops-infra/.github/workflows/cd.yml@develop
#   secrets: inherit
#   with:
#     repository: 'react-native-component'
#     version: '${{ needs.build.outputs.build_version }}'
#     environment: 'prod'
#     component: 'react-native'
