name: CI pipeline

on:
  push:
    branches:
      - main

    paths-ignore:
      - README.md
jobs:
  pipeline:
   used: susanto-dev/devops-infra/.github/workflows/pr-pipeline.yml
   secrets: inherit
   with:
     component: 'react-native'
