name: PR pipeline

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  actions: read
jobs:
  pipeline:
   uses: susanto-dev/devops-infra/.github/workflows/pr-pipeline.yml@develop
   secrets: inherit
   with:
     component: 'react-native'
